scripts.d/s-yacs
Pascal,
Pourrait-on activer les tests de yacs?
A+
=> s-yacs: activate yacs tests

scripts.d/.plan-ng-dev, scripts.d/s-python3-xlutils, scripts.d/s-salome-ng, scripts.d/s-salome-tar
Pascal, 
Cettes modifs pourrait corriger quelques tests de salome-ng :)
Bon wk
=> to activate MEDCOUPLING MPI TESTS and append some python module

scripts.d/.plan-ng-dev, scripts.d/s-salome-ng
Hello Pascal,
Pourrais tu intégrer mes modifs. Merci à toi.
A+
Duc
=> For OPENTURNS tests and the python simbolic link

scripts.d/s-netgen
Pascal c'est pour la petite correction sur s-netgen et pour mon test de push :)
=> s-netgen: Fix netgen PATH

scripts.d/.plan-ng-dev, scripts.d/s-salome-ng, scripts.d/s-zcracks
Fix native useless detection for debian 9
=> s-zcracks: Use in ng mode

scripts.d/s-salome-ng
Hello Pascal
some correction for 03_s_salome_bin.sh
A+
=> s-salome-ng: clean the environment of s-salome-bin

scripts.d/support/install-setup-ng
Je viens de corriger le commit. Merci Pascal
=> install-setup-ng: minor correction

scripts.d/support/servers.pvsc
Update server.pvsc file for remote viewing
=> servers.pvsc: Change method for remote connection

scripts.d/support/create_catalog_ng.sh
Salut Pascal,
Peux tu merger cela, stp?
Duc
=> create_catalog_ng.sh: minor correction for CatalogResource.xml

scripts.d/support/create_catalog_ng.sh
Pascal,
Un autre commit, stp :)
Merci
=> create_catalog_ng.sh: update the error handling

scripts.d/support/create_catalog_ng.sh
une petite correction pour le clustertest de gitlab-ci
=> create_catalog_ng.sh: fix salome installation check

scripts.d/.plan-cluster-ng-dev, scripts.d/support/install-setup-ng
Pull request to include fix server.pvsc copy
=> install-setup-ng: Fix server.pvsc file copy

scripts.d/support/create_catalog_ng.sh
Pull request to check remote repository access
=> create_catalog_ng.sh: Add remote repository access check

scripts.d/.env-cluster-ng-v910
SCBI_EXTRA_NG_MODULES for redhat
=> .env-cluster-ng-v910: SCBI_EXTRA_NG_MODULES

scripts.d/.plan-hydro-ng-dev
To manage installers for HYDRO
=> .plan-hydro-ng-dev: For installers

scripts.d/s-python-modules
=> s-python-modules: Add geopandas and shapely modules

scripts.d/s-python-modules
Hydro compiles with these modules for scibian10.
=> s-python-modules: Fix python modules with HYDRO for scibian10

scripts.d/s-hydrosolver, scripts.d/s-salome-bin
New Eficas variable needed by s-hydrosolver
=> s-hydrosolver: Add EFICAS_NOUVEAU_ROOT variable -> EFICAS_TOOLS_ROOT_DIR

scripts.d/s-python-modules
=> s-python-modules: Add y-py module for telemac

scripts.d/.plan-cluster-ng-dev, scripts.d/s-paravisaddons-edf
Variant cronos for s-paravisaddons-edf with rhl machine
=> s-paravisaddons-edf

scripts.d/.plan-hydro-ng-dev, scripts.d/s-python-modules
Fix hydro version version to master for all OS and fix jupyter-events==0.5.0 for s10 version
=> pull request for hydro s10

scripts.d/support/create_catalog_ng.sh
Hello Pascal,
Pourrais tu  intégrer cette modif dans le dépôt principal?
Merci
A+
=> create_catalog_ng.sh:append cpu number for localhost

scripts.d/.plan-hydro-ng-dev, scripts.d/s-python-modules
=> hydro-ng: Fix pyproj and proj versions

scripts.d/s-salome-ng
Pascal,
Voici la correction de DVAR. Pourrais tu le merger dans master? Merci
A+
Duc
=> s-salome-ng: correction DVAR

scripts.d/s-salome-tar
=> s-salome-tar: Remove HELLO PYHELLO from IHM

scripts.d/.plan-ng-dev
To change salome version from dev to DEV
=> .plan-ng-dev: Change s-salome-ng version for DEV

scripts.d/.env-cluster-ng-v911, scripts.d/.plan-cluster-ng-v911, scripts.d/.plan-ng-v911
=> plan-ng-v911: Fix version detection for tag V9_11_0b1

scripts.d/.env-cluster-ng-dev
=> .env-cluster-ng-dev: Add SALOME_FILE_BIG_OBJ_DIR variable

scripts.d/.env-cfd-dev
=> .env-cfd-dev: Fix

scripts.d/s-paravisaddons-edf
Hello Pascal,
J'ajoute le nouveau test dans paravisaddon-edf. Peux-tu valider mon commit?
MErci Pascal
A+
=> s-paravisaddons-edf: add ctest for paravisaddons-edf

scripts.d/s-paravisaddons-edf
=> s-paravisaddons-edf: add pv inference server link

scripts.d/patches/paravis-headless.patch, scripts.d/s-paravis
Salut Pascal,
C'est pour industrialiser egl sur cronos
A+
Duc
=> fix and add patch for headless support for paravis

scripts.d/s-salome-tar, scripts.d/support/install-setup
Hello Pascal,
C'est pour les icons du hello et pyhello.
Merci
A+
Duc
=> remove icon of pyhello et hello

scripts.d/s-salome, scripts.d/support/install-setup, scripts.d/support/salome_hpc_visu_servers.py, scripts.d/support/servers.pvsc
Hello Pascal,
C'est pour la visu à distance sur cronos
A+
Duc
=> correction for updating servers.pvsc
